### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by Greenknight9000** [ChenThread/candyk#6]
When using the Makefile, I am unable to compile the game, and researching the issue online returns no results
![image](https://github.com/ChenThread/candyk-psx/assets/91160044/2a5c26c0-1540-4ef4-99c9-bd041f35c2e8)

**Comment by asiekierka** [comment]
This isn't the right repository - https://github.com/ChenThread/fromage is for the game.

That is correct; there isn't exactly a supported way to compile the game right now. If I recall correctly, with the commit https://github.com/ChenThread/fromage/commit/6a7d543759d82b7d63852dbf845a7aa3a5b3a825 I patched it so that it requires the MIPS toolchain from https://wonderful.asie.pl/docs/getting-started/ , but the libraries from `candyk-psx`. You might need to revert some of that to get it to use CandyK's old compiler/libc.
